version: '2'

services:

  wordpress:
    image: wordpress:latest 
    volumes:
      - ./wp-app:/var/www/html 
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: thisispassword

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306 # change ip if required
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: thisispassword
